<!DOCTYPE html>

<html lang="en">

  <head>

      <meta charset="UTF-8">

      <script>
        function digitalClock() {
          var date = new Date();
          var hours = date.getHours();
          var minutes = date.getMinutes();
          var seconds = date.getSeconds();

          if (hours < 10) hours = "0" + hours;
          if (minutes < 10) minutes = "0" + minutes;
          if (seconds < 10) seconds = "0" + seconds;
            document.getElementById("id_clock").innerHTML = hours + ":" + minutes + ":" + seconds;
            setTimeout("digitalClock()", 1000);
        }
        </script>

      <title>My first web page</title>

  </head>

  <body>

  <header>

    <img src="https://www.w3schools.com/images/lamp.jpg" alt="Some image" width="480" height="240"
     style="border:5px solid green; margin-left: 700px; border-radius: 10px">

  </header>

  <main>

    <h3>About me</h3>
    <h3>Experience</h3>
    <h3>Projects</h3>
    <h4>
      <div id="id_clock"></div> 
      <script>digitalClock();</script>
    </h4>

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. At aut dolorum eaque eius explicabo fugit hic ipsa ipsum
      iste maxime modi necessitatibus nulla omnis quaerat, quam quos tempore totam voluptatum.</p>
    <p>Adipisci culpa doloremque id, nostrum porro repellat sit. Consequuntur inventore magnam sunt tempora? Amet
      consequuntur eligendi, excepturi hic impedit obcaecati perferendis perspiciatis placeat recusandae repellat sapiente
      temporibus, ut vel vitae?</p>
    <p>Aliquam eligendi facilis illum inventore ipsa non nostrum, quidem quos soluta veniam. Ab asperiores debitis
      dignissimos esse exercitationem iste, tempore voluptatibus. Laborum non numquam provident quisquam recusandae?
      Consequatur, sit, unde?</p>
    <p>Atque debitis dolorum earum fugiat maxime minus neque quaerat quia, ratione repellendus vel velit! Adipisci aliquid
      deleniti eos facere ipsa iure laboriosam pariatur praesentium quam repellat soluta velit veniam, voluptatem.</p>

  </main>

  <footer>
    <ul>
      <li><a href="https://www.linkedin.com/in/oleksii-korchynskyi-4a58031b9/">LinkedIn</a></li>
      <li><a href="https://github.com/AlekseyKor">GitHub</a></li>
      <li><a href="mailto:maritimealeksey@gmail.com">Email</a></li>
      <li><a href="tel:+4407361272880">Phone number</a></li>
    </ul>
  </footer>

  </body>
</html>